config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'admin/login'

  get 'admin/index'

  get 'admin/loan'

  namespace :admin do
    resources :books, :members
  end
  
  resources :admins
  resources :member
  
  root              'static_pages#home'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  
  get 'member'   =>  'member#index'
  get 'admin'    =>   'admin#index'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  match 'admin/assign',      to: 'admin#assign',        via: 'post'
  match 'admin/returned',      to: 'admin#returned',        via: 'post'
  match 'member/renew', to: 'member#renew', via: 'post'
  
end

app/models/book.rb
class Book < ActiveRecord::Base
    
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
  end

  # GET /books/new
  def new
    @book = Book.new
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
  end

  # GET /books/1/edit
  def edit
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end

    respond_to do |format|
      if @book.save
        format.html { redirect_to admin_books_url, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
    
    
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to admin_books_url, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
    
    if !@book.isactivebook
      @book.destroy
      respond_to do |format|
        format.html { redirect_to admin_books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_books_url, notice: 'This book is still active, cannot be destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :description, :author, :image, :member_id, :end_date, :max_end_date, :last_member_id, :last_loan_date, :isactivebook, :reason)
    end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.number_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :member_id %> ID<br>
    <%= f.number_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :max_end_date %><br>
    <%= f.datetime_select :max_end_date %>
  </div>
  <div class="field">
    <%= f.label :last_member_id %> ID<br>
    <%= f.number_field :last_member_id %>
  </div>
  <div class="field">
    <%= f.label :last_loan_date %><br>
    <%= f.datetime_select :last_loan_date %>
  </div>
  <div class="field">
    <%= f.label :isactivebook %><br>
    <%= f.check_box :isactivebook %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_book_path(@book) %> |
<%= link_to 'Back', admin_books_path %>

app/views/admin/books/index.html.erb
<h1>Listing Books</h1>
<table id="race" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Isbn</th>
      <th>Description</th>
      <th>Author</th>
      <th>Image</th>
      <th>Member ID</th>
      <th>Due date</th>
      <th>Max due date</th>
      <th>Last member ID</th>
      <th>Returned date</th>
      <th>Isactivebook</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.isbn %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td class="book_image"><%= image_tag(book.image, alt: "rails logo") %></td>
        <td><%= book.member_id %></td>
        <td><%= book.end_date %></td>
        <td><%= book.max_end_date %></td>
        <td><%= book.last_member_id %></td>
        <td><%= book.last_loan_date %></td>
        <% if book.isactivebook %>
          <td><p>Active</p></td>
          <td><p>/</p></td>
        <% else %>
          <td><p>Inactive</p></td>
          <td><%= book.reason %></td>
        <% end %>
        <td><%= link_to 'Show', admin_book_path(book) %></td>
        <td><%= link_to 'Edit', edit_admin_book_path(book) %></td>
        <td><%= link_to 'Destroy', admin_book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Book', new_admin_book_path %>

app/views/admin/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_books_path %>

app/views/admin/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Image:</strong>
  <%= @book.image %>
</p>

<p>
  <strong>Member:</strong>
  <%= @book.member_id %>
</p>

<p>
  <strong>End date:</strong>
  <%= @book.end_date %>
</p>

<p>
  <strong>Max end date:</strong>
  <%= @book.max_end_date %>
</p>

<p>
  <strong>Last member:</strong>
  <%= @book.last_member_id %>
</p>

<p>
  <strong>Last loan date:</strong>
  <%= @book.last_loan_date %>
</p>

<p>
  <strong>Isactivebook:</strong>
  <%= @book.isactivebook %>
</p>

<%= link_to 'Edit', edit_admin_book_path(@book) %> |
<%= link_to 'Back', admin_books_path %>