config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'admin/login'

  get 'admin/index'

  get 'admin/loan'

  namespace :admin do
    resources :books, :members
  end
  
  resources :admins
  resources :member
  
  root              'static_pages#home'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  
  get 'member'   =>  'member#index'
  get 'admin'    =>   'admin#index'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  match 'admin/assign',      to: 'admin#assign',        via: 'post'
  match 'admin/returned',      to: 'admin#returned',        via: 'post'
  match 'member/renew', to: 'member#renew', via: 'post'
  
end

app/models/member.rb
class Member < ActiveRecord::Base
    before_save { self.login = login.downcase }
    validates :login, presence: true, length: { minimum: 1 }
    has_secure_password
    validates :password, presence: true, length: { minimum: 1 }
    
    # Returns the hash digest of the given string.
    #  def Member.digest(string)
    #    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    #                                                  BCrypt::Engine.cost
    #  BCrypt::Password.create(string, cost: cost)
    # end
    def full_name
        "#{self.firstname} #{self.lastname}"
    end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
    
  end

  # GET /members/1
  # GET /members/1.json
  def show
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
  end

  # GET /members/new
  def new
    @member = Member.new
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
    
  end

  # GET /members/1/edit
  def edit
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
    

    respond_to do |format|
      if @member.save
        format.html { redirect_to admin_members_url, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
    
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to admin_members_url, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in. #notlogin"
    else
      #si on essaye d'accéder à une page alors qu'on est pas admin
       if current_member.isadmin == false || current_member.isadmin.nil?
        redirect_to current_member, notice: "You can only access to your account details #notadmin"
      end
    end
    
    if !@member.isactivemember
      @member.destroy
      respond_to do |format|
        format.html { redirect_to admin_members_url, notice: 'Member was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_books_url, notice: 'This member is still active, cannot be destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:login, :password, :firstname, :lastname, :address1, :address2, :phoneno, :isactivemember, :isadmin)
    end
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  
  def index
    @books = Book.all
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in."
    end
  end
  
  def show
    @books = Book.all
    
    #Restrict accesss
    if current_member.nil?
      redirect_to login_path, notice: "You cannot access here before log in."
    else
      #si on essaye d'accéder à une page qui nexiste pas
      if Member.exists?(params[:id])
        @member = Member.find(params[:id])
        
          #si on essaye d'accéder à une page qui n'est pas la notre
           if @member.id != current_member.id
            redirect_to current_member, notice: "You can only access to your account details"
           end
      else
        @member = nil
        redirect_to current_member, notice: "You can only access to your account details #"
      end
    end
  end
  
  def renew
    @b = Book.find(params[:id])
    
    if @b.member_id == current_member.id #Renew Book
      if @b.max_end_date && (@b.max_end_date > DateTime.now)
        if @b.max_end_date > @b.end_date + 30.days
          @b.end_date = @b.end_date + 30.days
        else
          if @b.end_date == @b.max_end_date
            flash[:danger] = "You can't renew, you have reached your limit (90 days) for this book"
            redirect_to current_member
            return
          else
            @b.end_date = @b.max_end_date
          end
        end
      end
    end
    @b.save
    flash[:success] = "Book renewed !"
    redirect_to current_member
  end
  
  def new
    @member = Member.new
    
    #Restrict accesss
    if current_member.blank?
      redirect_to login_path, notice: "You cannot access here before log in."
    end
  end

  def create
    @member = Member.new(user_params)
    
    #Restrict accesss
    if current_member.blank?
      redirect_to login_path, notice: "You cannot access here before log in."
    end
    
    if @member.save
      log_in @member
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @member
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:member).permit(:login, :password, :firstname, :lastname, :address1, :address2, :phoneno, :isactivemember)
    end
  
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/member_helper.rb
module MemberHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(member)
    gravatar_id = Digest::MD5::hexdigest(member.login.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: member.firstname, class: "gravatar")
  end
end

app/views/admin/members/_form.html.erb
<%= form_for [:admin, @member] do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :phoneno %><br>
    <%= f.text_field :phoneno %>
  </div>
  <div class="field">
    <%= f.label :isactivemember %><br>
    <%= f.check_box :isactivemember %>
  </div>
  <div class="field">
    <%= f.label :isadmin %><br>
    <%= f.check_box :isadmin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_member_path(@member) %> |
<%= link_to 'Back', admin_members_path %>

app/views/admin/members/index.html.erb
<h1>Listing Members</h1>
<table id="members" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>ID</th>
      <th>Login</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Phone No</th>
      <th>Status</th>
      <th>IsAdmin</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= member.login %></td>
        <td><%= member.firstname %></td>
        <td><%= member.lastname %></td>
        <td><%= member.address1 %></td>
        <td><%= member.address2 %></td>
        <td><%= member.phoneno %></td>
        <td>
          <% if member.isactivemember != 0 %>
            <p>Active</p>
          <% else %>
            <p>Inactive</p>
          <% end %>
        </td>
        <td>
          <% if member.isadmin %>
            <p>Yes</p>
          <% else %>
            <p>No</p>
          <% end %>
        </td>
        <td><%= link_to 'Show', admin_member_path(member) %></td>
        <td><%= link_to 'Edit', edit_admin_member_path(member) %></td>
        <td><%= link_to 'Destroy', admin_member_path(member), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Member', new_admin_member_path %>

app/views/admin/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_members_path %>

app/views/admin/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @member.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @member.password %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @member.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @member.lastname %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @member.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @member.address2 %>
</p>

<p>
  <strong>Phoneno:</strong>
  <%= @member.phoneno %>
</p>

<p>
  <strong>Isactivemember:</strong>
  <%= @member.isactivemember %>
</p>

<%= link_to 'Edit', edit_admin_member_path(@member) %> |
<%= link_to 'Back', admin_members_path %>