config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'admin/login'

  get 'admin/index'

  get 'admin/loan'

  namespace :admin do
    resources :books, :members
  end
  
  resources :admins
  resources :member
  
  root              'static_pages#home'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  
  get 'member'   =>  'member#index'
  get 'admin'    =>   'admin#index'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  match 'admin/assign',      to: 'admin#assign',        via: 'post'
  match 'admin/returned',      to: 'admin#returned',        via: 'post'
  match 'member/renew', to: 'member#renew', via: 'post'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Website <a href="<%=root_url %>">Online Library</a> by Theo Creach and William Guezennec
    </small>
    <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
       <div class = "navbar-header">
          <button type = "button" class = "navbar-toggle" 
             data-toggle = "collapse" data-target = "#example-navbar-collapse">
             <span class = "sr-only">Toggle navigation</span>
             <span class = "icon-bar"></span>
             <span class = "icon-bar"></span>
             <span class = "icon-bar"></span>
          </button>
          <a class = "navbar-brand" href = "<%=root_url %>">Online Library</a>
       </div>
       
       <div class = "collapse navbar-collapse" id = "example-navbar-collapse">
          <ul class = "nav navbar-nav navbar-right">
             <li><%= link_to "Home", root_url %></li>
             <% if logged_in? %>
                <% if current_member.isadmin == true %>
                <li><%= link_to "Admin", admin_index_path %></li>
                <% end %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_member %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Log out", logout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
          </ul>
       </div>
    </nav>
  </div>
</header>
  
<% if logged_in? %>
  <% if current_member.isadmin == true %>
    <% if request.original_url.include?(admin_index_path) || request.original_url.include?(admin_members_path) || request.original_url.include?(admin_books_path) %>
      <div class="container nav_admin">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Admin Index", admin_index_path %></li>
            <li><%= link_to "Members", admin_members_path %></li>
            <li><%= link_to "Books", admin_books_path %></li>
          </ul>
      </div>
    <% end %>
  <% end %>
<% end %>
  
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  <meta name="author" content="Theo Creach + William Guezennec">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag     'application',  media: 'all',
                                              'data-turbolinks-track' => true %>
  <%= javascript_include_tag  'application',  'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
  
</head>
<body>
  
  <%= render 'layouts/header' %>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
  
  <%= render 'layouts/footer' %>

</body>
</html>